language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: idp4C65sg2m1WdGqlJYEAntRuPRQASqW3wKCh7SfNz3Hc565pKAT2bU/CCca5FNmT5kYiXS2a4flOxgPy51OVFjUS6qeR6Ld6OU/7S63b+f6sX7GB/cmKg6PcIDnzyFlVKP6o1nkjW1cyH6tKCKaVyH2NkX9ge0pjd5s4k6zlN/rlJIeKQl08VDg+qql+M1B+NJybzQPnv9S/hHcGdfnReMqNb2ANOo9MbUhOZnhV9KvH53lgMWb1sixNz5pKKehP0YfFUoKFwDNEl1ydkrwkVwBDPf/ShaUWLu/G8hMtaysv1XHGqcdNVLY+BIbFEzmLKGLAXQcexDaXBBZhvAiCUQIoteXdebAvLmzU2m63f96Jm+wtbOoieTylOq7h3hm+vMihLc525RklqvHI/OREP2Rcb+egwoCX8e6c1PaZq9x6Vw5JhJ3TvCjPf1+UpNuBnhg2Ar0yQ3/dPZFcTE8sZeLQkb/hi9uI8H9GwmSlKsTDDwUNpYhCq5cjanQrHTlV3VRZryhKTwSPieck6eC7ydRQ0DE1ikS5TQbeagS1eYaWJWHSZoQatyu0fbCJH4jd9tCeRtiGy6nfgAfBS3bv+FQg3vFq0+cbCQi0Bx265N5zLr96O6SHrKPo7jCw038dX9uHNfqYtqW5j3Kr45Rp7S3/R6NNE5fjnCDsndGQao=
