version: '2'
services:
  app:
    container_name: app-$ENV-$APP_VERSION
    image: isaac-app-$APP_VERSION
    networks:
      default:
        aliases:
          - app-$ENV
  api:
    container_name: api-$ENV-$API_VERSION
    image: isaac-api-$API_VERSION
    external_links:
      - $ES:elasticsearch
      - $PG:postgres
    networks:
      default:
        aliases:
          - api-$ENV-$API_VERSION
    volumes:
      - /local/data/conf:/local/data/rutherford/conf
      - /local/data/rutherford-content:/local/data/rutherford/git-contentstore/rutherford-content
      - /local/data/keys:/local/data/rutherford/keys

networks:
  default:
    external:
      name: isaac
