version: '2'
services:
  equality-checker:
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    logging:
      driver: journald
      options:
        tag: equality-checker
    restart: always
  chemistry-checker:
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - /local/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "$LOCAL_RED_NETWORK_IP:9200:9200"
      - "$LOCAL_RED_NETWORK_IP:9300:9300"
    restart: always

volumes:
  es-data:
    external:
      name: es-data

networks:
  default:
    external:
      name: isaac
