version: '2'
services:
  es-tracking:
    container_name: es-tracking
    image: elasticsearch:1.4
  es-live:
    container_name: es-live
    image: elasticsearch:1.4
  pg-live:
    container_name: pg-live
    image: isaac-pg
    volumes_from:
      - container:pgstore-live
  pg-dev:
    container_name: pg-dev
    image: isaac-pg
    volumes_from:
      - container:pgstore-dev
networks:
  default:
    external:
      name: isaac
