# For Elasticsearch to store its indexes, we usually need to increase the host machine's mmap count: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
# If `sysctl vm.max_map_count` is < 262144, then `sysctl -w vm.max_map_count=262144` and set vm.max_map_count in /etc/sysctl.conf to the same value # elasticsearch(lx) had 16777215
version: '2'
services:

  equality-checker:
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    logging:
      driver: journald
      options:
        tag: equality-checker
    restart: unless-stopped

  chemistry-checker:
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    restart: unless-stopped

  phy-elastic-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: phy-elastic-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - cluster.name=isaac-phy-live-content
      - "network.host=${LOCAL_PHY_ELASTIC_IP}"
      - "discovery.seed_hosts=${REMOTE_PHY_ELASTIC_IP},${LOCAL_PHY_ELASTIC_IP}" # master-eligible nodes
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - bootstrap.memory_lock=true # part of disabling swap
      # VV UN-COMMENT FOR BOOTSTRAP VV #
      # - "node.name=master"
      # - "cluster.initial_master_nodes=master"
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: -1 # doc suggestion: at least 2,048 our docker default is unlimited
      nofile: 1048576 # doc suggestion: at least 65,536
    volumes:
      - phy-content:/usr/share/elasticsearch/data
    networks:
      default:
        ipv4_address: "${LOCAL_PHY_ELASTIC_IP}"
    restart: unless-stopped

  cs-elastic-live:
    # container configuration https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    container_name: cs-elastic-live
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - cluster.name=isaac-cs-live-content
      - "network.host=${LOCAL_CS_ELASTIC_IP}"
      - "discovery.seed_hosts=${REMOTE_CS_ELASTIC_IP},${LOCAL_CS_ELASTIC_IP}" # master-eligible nodes
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - bootstrap.memory_lock=true # part of disabling swap
      # VV UN-COMMENT FOR BOOTSTRAP VV #
      # - "node.name=master"
      # - "cluster.initial_master_nodes=master"
    ulimits:
      memlock: -1 # part of disabling swap
      nproc: -1 # doc suggestion: at least 2,048 our docker default is unlimited
      nofile: 1048576 # doc suggestion: at least 65,536
    volumes:
      - cs-content:/usr/share/elasticsearch/data
    networks:
      default:
        ipv4_address: "${LOCAL_CS_ELASTIC_IP}"
    restart: unless-stopped

volumes:
  phy-content:
    external:
      name: phy-content
  cs-content:
    external:
      name: cs-content

networks:
  default:
    external:
      name: isaac
