# Step : Download dependencies so that they are cached in the docker layer if the pom file doesn't change
FROM maven:3-eclipse-temurin-22 AS target
WORKDIR /isaac-api
COPY pom.xml .
RUN mvn dependency:go-offline
