global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus_exporter'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'elasticsearch_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['elasticsearch-exporter:9108']

  - job_name: 'isaac_api_exporter'
    metrics_path: '/metrics'
    static_configs:
      # Use one of the names/addresses returned by:
      # python -c 'import socket;print(socket.gethostbyname_ex(socket.gethostname()))'
      - targets: ['YOUR_IP_ADDRESS:9966']
