name: Checkstyle

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checkstyle:
    name: Checkstyle
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info
          checkstyle_config: src/main/resources/checkstyle-config.xml
          fail_on_error: true
