# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-  
    - name: Fetch ES data
      run: wget -O src/test/resources/isaac-test-es-data.tar.gz https://cdn.isaacscience.org/test/isaac-test-es-data.tar.gz
    - name: Debug permissions
      run: ls -lah src/test/resources/isaac-test-es-docker-entrypoint.sh
    - name: Set ES custom entrypoint script as executable
      run: chmod 775 src/test/resources/isaac-test-es-docker-entrypoint.sh && chown root:root src/test/resources/isaac-test-es-docker-entrypoint.sh
    - name: Debug permissions
      run: ls -lah src/test/resources/isaac-test-es-docker-entrypoint.sh
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
#    - name: Test with Maven
#      run: mvn -B test --file pom.xml
#    - uses: codecov/codecov-action@v2
