# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, main, 'robert/104-coverage-spike-testing' ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-  
    - name: Fetch ES data
      run: wget -O src/test/resources/isaac-test-es-data.tar.gz https://cdn.isaaccomputerscience.org/isaac/test/isaac-test-es-data.tar.gz
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Test with Maven
      run: mvn -B verify --file pom.xml
    - name: Add coverage to PR
      id: jacocof
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/**/target/site/jacoco-merged-test-coverage-report/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: Coverage Report # A title is required for update-comment to work correctly
        update-comment: true
        pass-emoji: ':white_check_mark:'
        fail-emoji: ':x:'
        continue-on-error: true # The repository is currently far below the threshold, so we can't enforce this for now
