name: Publish ETL Docker image

on:
  push:
    branches: [main]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-etl-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta etl
        id: meta-etl
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-etl
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
      - name: sha short
        if: github.ref_type == 'branch'
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push etl Docker image sha
        uses: docker/build-push-action@v5
        if: github.ref_type == 'branch'
        with:
          context: .
          push: true
          build-args: |
            MVN_PACKAGE_PARAM=-P etl
            BUILD_VERSION=${{ steps.sha.outputs.sha_short }}
          tags: ${{ steps.meta-etl.outputs.tags }}
          labels: ${{ steps.meta-etl.outputs.labels }}
      - name: Build and push etl Docker image tag
        uses: docker/build-push-action@v5
        if: github.ref_type == 'tag'
        with:
          context: .
          push: true
          build-args: |
            MVN_PACKAGE_PARAM=-P etl
            BUILD_VERSION=${{ github.ref_name }}
          tags: ${{ steps.meta-etl.outputs.tags }}
          labels: ${{ steps.meta-etl.outputs.labels }}
