name: Publish ETL Docker image

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-etl-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta etl
        id: meta-etl
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-etl
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
      - name: Build and push etl Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            MVN_PACKAGE_PARAM=-P etl
          tags: ${{ steps.meta-etl.outputs.tags }}
          labels: ${{ steps.meta-etl.outputs.labels }}